### ISSUE TITLE
were we need to upload our session id

### ISSUE THREAD

**Issue by Hareshkumar77** [EchterAlsFake/Osintgram2#7]

**Comment by EchterAlsFake** [comment]
Hi,

Sorry, but I do not really understand your question. Do you mean "why we need to upload our session id"?  

You don't upload the session id. It's saved on your computer, so that if you re-use the tool the login is faster. If you login all the time to Instagram you get blocked really fast. That's why I am using the session id. But ít won't be uploaded or shared with others at any time.
